#!/bin/bash
#Turn off Power saver and Screen Blanking
sleep 1;xset s off -dpms
sleep 1;xset s noblank
#sleep 1; xset s dpms 20 20
# If Chrome crashes (usually due to rebooting), clear the crash flag so we don't have the annoying warning bar sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' /home/pi/.config/chromium/Default/Preferences sed -i 's/"exit_type":"Crashed"/"exit_type":"Normal"/' /home/pi/.config/chromium/Default/Preferences
#hide mouse cursor
unclutter -idle 1 &
#Execute window manager for full screen
exec matchbox-window-manager -use_titlebar no &
#matchbox-keyboard &
#Execute Browser with options
chromium-browser --noerrdialogs --disable-pinch --kiosk http://localhost:3000/public/login.html